version: "3"
services:

 Squid:
  image: sameersbn/squid:3.5.27-2
  container_name: squid
  ports:
    - 3128:3128
  volumes:
    - ./squid.conf:/etc/squid/squid.conf
  networks:
    - kong

 postgres:
  extends:
   file: ../../base/db.yml
   service: postgres

 kong-ent-bootstrap:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent-bootstrap
  depends_on:
   - postgres
  networks:
   - kong
  environment:
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong

 kong-ent:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent
  depends_on:
   - postgres
   - kong-ent-bootstrap
  networks:
   - kong
  extra_hosts:
   - "python:10.0.0.1"
  environment:
#  - KONG_ENFORCE_RBAC=on
#  - KONG_ADMIN_GUI_AUTH=basic-auth
#  - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
  - KONG_DATABASE=postgres
  - KONG_PG_HOST=postgres
  - KONG_PG_PASSWORD=kong

networks:
  kong:
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/24 
