version: "3"
services:

 redis:
  extends:
   file: ../../base/redis.yml
   service: redis

 collector-database:
  extends:
   file: ../../base/db.yml
   service: postgres
  container_name: collector-database
  environment:
   - POSTGRES_USER=collector
   - POSTGRES_DB=collector
   - POSTGRES_PASSWORD=collector

 collector-bootstrap:
  image: kong/immunity:4.1.0
  container_name: collector-bootstrap
  networks:
   - kong
  restart: on-failure
  depends_on:
   - collector-database
  command: "flask db upgrade"
  environment:
   - SQLALCHEMY_DATABASE_URI=postgres://collector:collector@collector-database:5432/collector

 collector:
  image: kong/immunity:4.1.0
  container_name: collector
  networks:
   - kong
  restart: always
  depends_on:
   - redis
   - collector-database
   - collector-bootstrap
  environment:
   - SQLALCHEMY_DATABASE_URI=postgres://collector:collector@collector-database:5432/collector
   - CELERY_BROKER_URL=redis://redis:6379/0
   - KONG_HOST=kong-ent
   - KONG_PORT=8001
  ports:
   - 5000:5000
  
 celery-beat:
  image: kong/immunity:4.1.0
  container_name: celery-beat
  networks:
   - kong
  depends_on:
   - redis
   - collector-database
   - collector-bootstrap
  command: "celery beat -l info -A collector.scheduler.celery"
  environment:
   - CELERY_BROKER_URL=redis://redis:6379/0
  
 celery-worker:
  image: kong/immunity:4.1.0
  container_name: celery-worker
  networks:
   - kong
  depends_on:
   - redis
   - collector-database
   - collector-bootstrap
  command: "celery worker -l info -A collector.scheduler.celery --concurrency=1"
  environment:
   - SQLALCHEMY_DATABASE_URI=postgres://collector:collector@collector-database:5432/collector
   - CELERY_BROKER_URL=redis://redis:6379/0
   - KONG_HOST=kong-ent
   - KONG_PORT=8001

 postgres:
  extends:
   file: ../../base/db.yml
   service: postgres

 kong-ent-bootstrap:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent-bootstrap
  depends_on:
   - postgres
  networks:
   - kong
  environment:
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong

 kong-ent:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent
  depends_on:
   - postgres
   - kong-ent-bootstrap
  networks:
   - kong
  extra_hosts:
   - "python:10.0.0.1"
  environment:
#  - KONG_ENFORCE_RBAC=on
#  - KONG_ADMIN_GUI_AUTH=basic-auth
#  - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
  - KONG_DATABASE=postgres
  - KONG_PG_HOST=postgres
  - KONG_PG_PASSWORD=kong

networks:
  kong:
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/24 
