version: "3"
services:

 vault:
  image: vault
  container_name: vault
  cap_add:
  - IPC_LOCK
  networks:
  - kong
  ports:
  - 8200:8200
  environment:
  - VAULT_ADDR=http://0.0.0.0:8200
  - VAULT_DEV_ROOT_TOKEN_ID=vault
  - VAULT_LOG_LEVEL=debug

 postgres:
  extends:
   file: ../../base/db.yml
   service: postgres

 kong-ent-bootstrap:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent-bootstrap
  depends_on:
   - postgres
  networks:
   - kong
  environment:
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong

 kong-ent:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent
  depends_on:
   - postgres
   - kong-ent-bootstrap
  networks:
   - kong
  extra_hosts:
   - "python:10.0.0.1"
  environment:
#  - KONG_ENFORCE_RBAC=on
#  - KONG_ADMIN_GUI_AUTH=basic-auth
#  - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
  - KONG_DATABASE=postgres
  - KONG_PG_HOST=postgres
  - KONG_PG_PASSWORD=kong
  - KONG_KEYRING_ENABLED=on
  - KONG_KEYRING_STRATEGY=vault
  - KONG_KEYRING_VAULT_HOST=http://vault:8200
  - KONG_KEYRING_VAULT_PATH=test
  - KONG_KEYRING_VAULT_MOUNT=kong
  - KONG_KEYRING_VAULT_TOKEN=vault

networks:
  kong:
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/24 
