version: "3"
services:

 ldap:
  image: osixia/openldap:1.3.0
  container_name: ldap
  networks:
   - kong
  ports:
   - 389:389
   - 636:636
  volumes:
   - ./new-user.ldif:/container/service/slapd/assets/test/new-user.ldif

 postgres:
  extends:
   file: ../../base/db.yml
   service: postgres

 kong-ent-bootstrap:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent-bootstrap
  depends_on:
   - postgres
  networks:
   - kong
  environment:
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong

 kong-ent:
  extends:
   file: ../../base/kong.base.yml
   service: kong-ent
  depends_on:
   - postgres
   - kong-ent-bootstrap
  networks:
   - kong
  ports:
   - 8000:8000
   - 8001:8001
   - 8002:8002
   - 8003:8003
   - 8004:8004
   - 8443:8443
   - 8444:8444
   - 8445:8445
   - 8446:8446
   - 8447:8447
  extra_hosts:
    - "python:10.0.0.1"
  environment:
   - KONG_ENFORCE_RBAC=on
   - KONG_ADMIN_GUI_AUTH=ldap-auth-advanced
   - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
   - KONG_ADMIN_GUI_AUTH_CONF={"anonymous":"","attribute":"uid","bind_dn":"cn=admin,dc=example,dc=org","base_dn":"dc=example,dc=org","cache_ttl":2,"header_type":"Basic","keepalive":60000,"ldap_host":"ldap","ldap_password":"admin","ldap_port":389,"start_tls":false,"timeout":10000,"verify_ldap_host":false,"consumer_by":["username","custom_id"]}
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong
networks:
  kong:
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/24 
